codeball:
  authorizationDomain: codete.com

spring:
  application:
    index: index.html
  resources:
    static-locations: classpath:/resources/,classpath:/static/,classpath:/META-INF/resources/

security:
  basic:
    enabled: false
  user:
    name: user
    password: pass
  oauth2:
    client:
      clientId: 645433820383-ks9c1u94qujptei3n7v6tuas2k4m9l1u.apps.googleusercontent.com
      clientSecret: QycJ9l6BRJvKtiuJJGPfLiS2
      accessTokenUri: https://accounts.google.com/o/oauth2/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth?hd=${codeball.authorizationDomain}
      authenticationScheme: query
      clientAuthenticationScheme: query
      scope: profile email
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v1/userinfo
      preferTokenInfo: false

development:
  securityContext:
    enabled: true
  user:
    email: development@codeball.com
    firstName: Codeball
    lastName: Developer
    pictureUrl: https://gpkt.files.wordpress.com/2008/05/012.jpg
    role: ROLE_ADMIN
